### ISSUE TITLE
Logo is not showing up.

### ISSUE THREAD

**Issue by dgarcu** [carlosperate/jekyll-theme-rtd#23]
Hi there!

I am trying to build a website. Apparently all is working nicely but tthe logo is not:

![image](https://github.com/carlosperate/jekyll-theme-rtd/assets/92941081/5f79f7c5-b98c-4d8d-b47f-3aac16989823)

This is my `_config.yml` file:

```yml
title: Mobile Robotics Blog
description: This blog will host the latest news regarding the development of the subjects practices
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Diego García Currás
repo_url: "https://github.com/dgarcu/mobile_robotics_blog"
edit_on_github: true
github_docs_folder: true
logo: './docs/assets/img/logo.png'
site_favicon: './docs/assets/img/favicon.ico'
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
```

The _favicon_ is showing up as expected, _btw_.

I think I followed the instructions in the docs, but apparently I am missing something. Maybe the issue is with the image. [Here](https://github.com/dgarcu/mobile_robotics_blog) you will find my repo where the page is being built and deployed, just in case you want to take a deeper look. The img is located at the path `./docs/assets/img/logo.png` of said repo.

Thanks in advance! Cheers!

Diego.

**Comment by dgarcu** [comment]
Hi there! I have fixed the problem.

After trying to include said logo in a regular page from the website, I realized that I have to use the relative path from the source code location for said page. I thought that maybe same applies for the `_config.yml` file, so I tryed to do so:

```yml
title: Mobile Robotics Blog
description: This blog will host the latest news regarding the development of the subjects practices
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Diego García Currás
repo_url: "https://github.com/dgarcu/mobile_robotics_blog"
edit_on_github: true
github_docs_folder: true
logo: 'assets/img/logo.png' # <- Here! 
site_favicon: './docs/assets/img/favicon.ico'
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
```

And that worked flawessly! 

![image](https://github.com/carlosperate/jekyll-theme-rtd/assets/92941081/0bc692d1-768b-4c3b-af4a-fb72fe32fe31)

Now I have the doubt of why the favicon is working as expected with the absolute path... Not gonna complain _tbh_.

Cheers!
